# Workflow สำหรับ deploy static content ไปที่ GitHub Pages
name: Deploy static content to Pages

on:
  # รันเมื่อ push ไปที่ branch หลัก
  push:
    branches: ["main"]

  # รองรับการรัน workflow แบบ manual
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # ตั้งค่า Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # อัปโหลด artifact ที่ต้องการ deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # Deploy ไปยัง GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
